package com.vadimtoptunov.chaosbank_android.core.defects

import com.vadimtoptunov.chaosbank_android.core.defects.DefectCategory.*
import com.vadimtoptunov.chaosbank_android.core.defects.Flakiness.*
import com.vadimtoptunov.chaosbank_android.core.defects.Severity.*

/** The single catalog. Every defect is declared here exactly once, with its category. */
object DefectRegistry {

    private fun d(
        id: DefectId, title: String, feature: String, category: DefectCategory,
        severity: Severity, violates: String, flakiness: Flakiness = deterministic,
    ) = Defect(id, title, feature, category, severity, violates, flakiness)

    val all: List<Defect> = listOf(
        // Money / logic
        d(DefectId.roundingDrift, "Conversion rounds wrong into history", "Exchange / Order", Money, major,
            "Displayed value and stored value are identical, correctly rounded (Decimal)."),
        d(DefectId.pnlSign, "Loss displayed as gain", "Portfolio", Money, critical,
            "P&L sign matches actual gain/loss."),
        d(DefectId.exchangeFeeNotApplied, "Exchange ignores the fee it displays", "Exchange", Money, major,
            "The credited amount reflects the displayed fee."),
        d(DefectId.pnlPercentVsValue, "P&L % divides by market value, not cost", "Portfolio", Money, major,
            "P&L percent is measured against cost basis."),
        d(DefectId.homeTotalOmitsAccount, "Total balance omits an account", "Home", Money, major,
            "Total balance sums every account."),
        d(DefectId.balanceFloorRounded, "Total balance floored, not rounded", "Home", Money, minor,
            "Balances round to the nearest cent."),
        d(DefectId.todayChangeSignFlipped, "Today's change sign flipped", "Home", Money, major,
            "The daily change sign matches the actual move."),
        d(DefectId.transferDebitsWrongAccount, "Transfer debits the wrong account", "Transfer", Money, critical,
            "A transfer debits the selected account."),
        d(DefectId.balanceAfterAdds, "'Balance after' adds instead of subtracts", "Transfer", Money, major,
            "Balance-after = balance − amount."),
        d(DefectId.transferRoundsUp, "Transfer amount rounded up", "Transfer", Money, major,
            "The exact amount is transferred."),
        d(DefectId.exchangeInverseRate, "Exchange uses the inverse rate", "Exchange", Money, critical,
            "Conversion uses the correct directional rate."),
        d(DefectId.exchangeCreditsWrongAccount, "Exchange credits the wrong account", "Exchange", Money, critical,
            "The bought currency lands in its account."),
        d(DefectId.exchangeFeeDoubled, "Exchange fee charged twice", "Exchange", Money, major,
            "The fee is charged once."),
        d(DefectId.youGetShowsGross, "'You get' shows the pre-fee amount", "Exchange", Money, major,
            "'You get' shows the net, post-fee amount."),
        d(DefectId.loanAprUnderstated, "Loan APR understated vs the rate charged", "Loans", Money, critical,
            "The advertised APR equals the rate used to compute the monthly payment."),
        d(DefectId.changePctSignFlipped, "Market % change sign flipped", "Markets", Money, major,
            "The percent change sign matches the price move."),
        d(DefectId.detailPriceOffset, "Asset detail price is offset", "Asset detail", Money, major,
            "The detail price matches the market price."),
        d(DefectId.detailChangeWrongBase, "Detail % uses base, not day open", "Asset detail", Money, minor,
            "Percent change is measured against the day open."),
        d(DefectId.estTotalIgnoresQty, "Order total ignores quantity", "Order", Money, critical,
            "Estimated total = quantity × price."),
        d(DefectId.limitExecutesAtMarket, "Limit order executes at market", "Order", Money, major,
            "A limit order executes at the limit price."),
        d(DefectId.holdingValueUsesCost, "Holding value uses cost, not price", "Portfolio", Money, major,
            "Position value uses the live price."),
        d(DefectId.totalValueOmitsHolding, "Portfolio total omits a holding", "Portfolio", Money, major,
            "Invested value sums every holding."),
        d(DefectId.pnlPercentAbsOnly, "P&L % shown as absolute value", "Portfolio", Money, major,
            "P&L percent keeps its sign."),

        // Validation
        d(DefectId.limitValidation, "Bad limit orders accepted silently", "Order", Validation, major,
            "Limit sell below market warns; qty must be > 0."),
        d(DefectId.zeroAmountAccepted, "Zero-amount transfer allowed", "Transfer", Validation, major,
            "Continue requires an amount greater than zero."),
        d(DefectId.whitespaceRecipient, "Recipient whitespace not trimmed", "Transfer", Validation, minor,
            "Leading/trailing whitespace is trimmed before validation."),
        d(DefectId.passcodeWeakAccepted, "Short passcode accepted", "Auth", Validation, major,
            "The app passcode must be the full required length."),
        d(DefectId.amountExceedsBalanceAllowed, "Transfer over balance allowed", "Transfer", Validation, major,
            "Continue is blocked when the amount exceeds the balance."),
        d(DefectId.transferNegativeCredits, "Negative transfer amount accepted", "Transfer", Validation, major,
            "Transfer amounts must be positive."),
        d(DefectId.exchangeSameCurrencyAllowed, "Exchange to the same currency allowed", "Exchange", Validation, minor,
            "Sell and get currencies must differ."),
        d(DefectId.searchCaseSensitive, "Transaction search is case-sensitive", "Transactions", Validation, minor,
            "Search is case-insensitive."),
        d(DefectId.sellWithoutHoldingReviewable, "Sell reviewable with no holding", "Order", Validation, major,
            "You cannot review a sell you can't cover."),
        d(DefectId.orderQtyDefaultsZero, "Order quantity defaults to zero", "Order", Validation, minor,
            "The order ticket opens with a valid quantity."),
        d(DefectId.loginAcceptsEmptyCreds, "Login accepts empty credentials", "Auth", Validation, major,
            "Login requires a username and password."),
        d(DefectId.cardLimitAcceptsZero, "Card monthly limit accepts zero", "Card", Validation, minor,
            "The monthly limit must be positive."),

        // Localization
        d(DefectId.localeParse, "1,000.50 parsed as 1.00050", "Exchange / Transfer", Localization, major,
            "Amounts parse correctly under the active locale."),
        d(DefectId.dateTimezoneShift, "Transaction date shifts by timezone", "Transactions", Localization, minor,
            "Dates render in a stable, correct timezone."),
        d(DefectId.rtlBreaksLayout, "Row doesn't mirror under RTL", "Transactions", Localization, major,
            "Under a right-to-left layout, rows mirror correctly (start/end, not hard-coded left/right)."),
        d(DefectId.numberGroupingIgnoresLocale, "Number grouping ignores the locale", "Localization", Localization, major,
            "Grouping and decimal separators follow the selected locale (e.g. 1.234,56 in de-DE)."),
        d(DefectId.currencySymbolPlacementIgnoresLocale, "Currency symbol placed wrong for the locale", "Localization", Localization, major,
            "The currency symbol sits where the locale expects (before in en-US, after in de-DE)."),
        d(DefectId.balanceWrongCurrencySymbol, "Balance always shows the € symbol", "Home", Localization, major,
            "The currency symbol matches the selected currency."),
        d(DefectId.priceMissingDecimals, "Prices shown without decimals", "Markets", Localization, minor,
            "Prices show two fraction digits."),
        d(DefectId.searchTrimsNothing, "Search doesn't trim whitespace", "Transactions", Localization, minor,
            "Search input is trimmed before matching."),

        // State / navigation (paginationNeverEnds lives here — see below)
        d(DefectId.staleBalance, "Dashboard shows pre-transfer balance", "Home", State, major,
            "Balance reflects latest state after any mutation."),
        d(DefectId.paginationDup, "Transaction duplicated after Load more", "Transactions", State, minor,
            "Each transaction appears once."),
        d(DefectId.paginationNeverEnds, "Pagination never ends", "Transactions", State, major,
            "Pagination terminates once every matching row is shown."),
        d(DefectId.cardToggleInvert, "Freeze toggle reads back inverted", "Card", State, major,
            "Toggle state persists and reads back correctly."),
        d(DefectId.filterLeaksCategory, "Money-in filter leaks money-out rows", "Transactions", State, major,
            "A filter shows only its own category."),
        d(DefectId.orderStuckPending, "Filled order still shows pending", "Order", State, major,
            "A filled order reports filled, not pending."),
        d(DefectId.quickActionTransferOpensExchange, "Transfer action opens Exchange", "Home", State, major,
            "Each quick action opens its own screen."),
        d(DefectId.recentActivityShowsTwo, "Recent activity shows too few rows", "Home", State, minor,
            "Recent activity shows the last four items."),
        d(DefectId.exchangeRateStaleAfterSwap, "Rate stale after swapping direction", "Exchange", State, major,
            "The rate recomputes when the pair changes."),
        d(DefectId.filterOutLeaksIn, "Money-out filter leaks money-in rows", "Transactions", State, major,
            "A filter shows only its own category."),
        d(DefectId.searchIgnoresCategory, "Search ignores the category field", "Transactions", State, minor,
            "Search matches title and category."),
        d(DefectId.cryptoShownInStocks, "Crypto appears in the Stocks segment", "Markets", State, minor,
            "Each segment shows only its asset kind."),
        d(DefectId.watchlistShowsAll, "Watchlist shows every asset", "Markets", State, minor,
            "The watchlist shows only watched symbols."),
        d(DefectId.assetRowOpensWrongDetail, "Tapping an asset opens the wrong one", "Markets", State, critical,
            "Tapping a row opens that row's asset."),
        d(DefectId.buyButtonPlacesSell, "Buy opens a Sell order ticket", "Asset detail", State, critical,
            "The Buy button starts a buy order."),
        d(DefectId.buySellSwapped, "Buy side actually sells", "Order", State, critical,
            "The buy side buys."),
        d(DefectId.onlinePaymentsInverted, "Online-payments toggle reads inverted", "Card", State, major,
            "Toggle state persists and reads back correctly."),
        d(DefectId.transferConfirmWrongRecipient, "Confirm sheet shows wrong recipient", "Transfer", State, major,
            "The confirmation shows the entered recipient."),
        d(DefectId.notificationBadgeStale, "Notification badge stays stale", "Notifications", State, minor,
            "The unread badge reflects the actual unread count."),
        d(DefectId.notificationOpensWrongScreen, "Notification opens the wrong screen", "Notifications", State, major,
            "Tapping a notification opens the destination it names."),
        d(DefectId.templatePrefillsWrongAmount, "Payment template prefills the wrong amount", "Transfer / Templates", State, major,
            "Applying a saved template prefills its exact saved amount."),

        // Concurrency / races
        d(DefectId.doubleCharge, "Rapid double-tap sends twice", "Transfer", Concurrency, critical,
            "Confirm is idempotent; one tap = one transaction.", raceCondition),
        d(DefectId.livePriceRace, "Order price ≠ tapped price", "Markets / Order", Concurrency, critical,
            "Confirmation price equals the price acted on.", raceCondition),
        d(DefectId.orderDoubleSubmit, "Rapid double-tap places two orders", "Order", Concurrency, critical,
            "Place is idempotent; one tap = one order.", raceCondition),
        d(DefectId.exchangeDoubleSubmit, "Rapid double-tap exchanges twice", "Exchange", Concurrency, critical,
            "Execute is idempotent; one tap = one exchange.", raceCondition),
        d(DefectId.homeRefreshRace, "Overlapping refreshes clobber the dashboard", "Home", Concurrency, major,
            "A stale refresh never overwrites a newer one.", raceCondition),
        d(DefectId.syncLostUpdate, "Concurrent increments lose updates", "Sync", Concurrency, major,
            "Concurrent read-modify-write increments are atomic; none are lost.", raceCondition),

        // Performance
        d(DefectId.transactionsHeavyList, "History renders a huge non-lazy list", "Transactions", Performance, major,
            "Long lists render lazily and stay smooth."),
        d(DefectId.mainThreadStall, "Portfolio blocks the main thread on open", "Portfolio", Performance, major,
            "Work stays off the main thread; the UI never hangs."),
        d(DefectId.feedPollsTooOften, "Live feed polls 10× too often", "Markets", Performance, minor,
            "The live feed polls at a sane interval."),
        d(DefectId.transactionsSortEveryRender, "History re-sorts on every render", "Transactions", Performance, minor,
            "Expensive work is not redone on every render."),
        d(DefectId.sparklineHeavyPoints, "Sparklines compute thousands of points", "Markets", Performance, minor,
            "Sparklines use a small point budget."),
        d(DefectId.transactionsRegroupHeavy, "History regroups expensively each render", "Transactions", Performance, minor,
            "Grouping is not redone wastefully."),

        // UI / layout
        d(DefectId.disabledButtonTappable, "Button looks disabled but still fires", "Transfer", Ui, major,
            "A disabled-looking control is actually non-interactive."),
        d(DefectId.otpResendNoCooldown, "OTP resend ignores the cooldown", "Auth", Ui, minor,
            "Resend is blocked until the cooldown elapses."),
        d(DefectId.successToastMissing, "No success toast after a transfer", "Transfer", Ui, minor,
            "A successful action shows a confirmation toast."),
        d(DefectId.accountStripHidesGBP, "GBP account card hidden", "Home", Ui, minor,
            "All accounts appear in the strip."),
        d(DefectId.outgoingSignHidden, "Outgoing amounts shown without a minus", "Transactions", Ui, major,
            "Outgoing amounts show a leading minus."),
        d(DefectId.transactionCountWrong, "Transaction count label is wrong", "Transactions", Ui, minor,
            "The count reflects the filtered total."),
        d(DefectId.detailStatHighLowSwapped, "Day high/low stats swapped", "Asset detail", Ui, minor,
            "High ≥ low in the stats grid."),
        d(DefectId.qtyIncrementByTwo, "Quantity stepper increments by two", "Order", Ui, major,
            "The stepper changes quantity by one."),
        d(DefectId.cardExpiryInPast, "Card expiry shown in the past", "Card", Ui, minor,
            "The displayed expiry is in the future."),
        d(DefectId.otpAutoFillsCode, "OTP field pre-filled with the real code", "Auth", Ui, major,
            "The OTP field starts empty."),
        d(DefectId.successToastTooBrief, "Success toast flashes too briefly", "Transfer", Ui, minor,
            "Confirmation stays visible long enough to read."),
        d(DefectId.flakyAnimation, "Ticker flash animation is unstable", "Markets", Ui, minor,
            "Value-change animations complete within a stable, bounded time.", raceCondition),

        // Accessibility
        d(DefectId.duplicateAssetA11yId, "Two market rows share one identifier", "Markets", Accessibility, major,
            "Every element has a unique, stable accessibility identifier."),
        d(DefectId.missingA11yLabel, "Place-order button has no accessibility label", "Order", Accessibility, major,
            "Every control exposes a meaningful accessibility label."),
        d(DefectId.wrongA11yLabel, "Buy button is labelled 'Sell'", "Asset detail", Accessibility, critical,
            "A control's accessibility label matches its action."),
        d(DefectId.marketRowNoLabel, "Market rows expose no accessibility label", "Markets", Accessibility, major,
            "List rows expose a meaningful label."),
        d(DefectId.freezeToggleNoLabel, "Freeze toggle has no accessibility label", "Card", Accessibility, major,
            "Controls expose a meaningful label."),

        // Security / privacy
        d(DefectId.authBypass, "Gate skipped after backgrounding", "Auth", Security, critical,
            "Sensitive screens always require the gate."),
        d(DefectId.noPrivacyBlur, "Sensitive data visible in app switcher", "Card / Auth", Security, major,
            "Sensitive screens are obscured when the app is inactive."),
        d(DefectId.otpAcceptsExpired, "Expired OTP still accepted", "Auth", Security, critical,
            "An expired one-time code is rejected."),
        d(DefectId.otpNoLockout, "No lockout after repeated wrong OTP", "Auth", Security, critical,
            "Too many wrong codes locks the OTP step."),
        d(DefectId.sessionTimeoutDisabled, "Session never times out", "Auth", Security, major,
            "An idle session re-locks after the timeout."),
        d(DefectId.tokenInUserDefaults, "Session token stored in plain prefs", "Auth", Security, critical,
            "Secrets live in the Keystore, never in SharedPreferences."),
        d(DefectId.cardNumberFullyVisible, "Full card number shown unmasked", "Card", Security, critical,
            "The card PAN is masked except the last 4 digits."),
        d(DefectId.cardCvvVisible, "CVV shown on the card face", "Card", Security, critical,
            "The CVV is never displayed on screen."),
        d(DefectId.otpCodeInLog, "OTP code written to the console log", "Auth", Security, major,
            "Secrets are never logged."),
        d(DefectId.pinShownPlaintext, "PIN shown in plaintext", "Card", Security, major,
            "The PIN is masked until explicitly revealed."),
        d(DefectId.otpAcceptsAnyCode, "OTP accepts any 6-digit code", "Auth", Security, critical,
            "Only the correct OTP is accepted."),
        d(DefectId.passcodeAnyAccepted, "Passcode entry accepts any code", "Auth", Security, critical,
            "Only the stored passcode unlocks."),
        d(DefectId.passcodeStoredPlaintext, "Passcode stored in plain prefs", "Auth", Security, critical,
            "The passcode is never persisted in plaintext."),
        d(DefectId.credentialsInLog, "Login credentials written to the console", "Auth", Security, critical,
            "Credentials are never logged."),
        d(DefectId.deepLinkSkipsAuth, "Deep link opens a screen without auth", "Deep links", Security, critical,
            "A deep link still requires the auth gate before showing content."),
        d(DefectId.biometricUnlocksFromAnyStage, "Biometrics bypass the auth ladder", "Auth", Security, critical,
            "Biometrics are a fast re-entry only; they never skip initial login/OTP/passcode."),
        d(DefectId.kycBypassAllowsTransfer, "Unverified KYC still sends large transfers", "Transfer / KYC", Security, critical,
            "A large transfer is blocked until identity (KYC) is verified."),
        d(DefectId.virtualCardShowsRealPan, "Virtual card exposes the real card number", "Card", Security, critical,
            "A virtual card shows a distinct virtual number, never the real PAN."),

        // Network (scenario-driven backend)
        d(DefectId.retryDuplicate, "Retry after slow response duplicates the payment", "Transfer / Network", Network, critical,
            "Retries are idempotent; a retried request never double-posts.", raceCondition),
        d(DefectId.slowResponseRace, "Stale response overwrites fresh state", "Markets / Network", Network, major,
            "An out-of-order/late response never clobbers newer data.", raceCondition),
        d(DefectId.timeoutAsSuccess, "Timeout shown as a successful transfer", "Transfer / Network", Network, critical,
            "A failed/timed-out request is surfaced as an error, not success."),
        d(DefectId.staleOfflineBalance, "Offline cache shows an outdated balance", "Home / Network", Network, major,
            "A stale cache is refreshed or clearly marked as stale."),
        d(DefectId.balanceReadReturnsZero, "Balance read returns zero on error", "Home / Network", Network, major,
            "A read error is surfaced, not shown as a zero balance."),
        d(DefectId.transactionsDupOnFetch, "Every transaction fetched twice", "Transactions / Network", Network, major,
            "A fetch returns each row once."),
        d(DefectId.staleHoldingsAfterOrder, "Holdings read is stale after an order", "Portfolio / Network", Network, major,
            "Reads reflect the latest holdings."),
        d(DefectId.offlineBannerMissing, "No offline indicator while offline", "App / Network", Network, major,
            "When offline, the UI clearly indicates it and serves cached data."),
    )

    private val byId: Map<DefectId, Defect> = all.associateBy { it.id }

    fun defect(id: DefectId): Defect = byId.getValue(id)

    fun ids(category: DefectCategory): Set<DefectId> =
        all.filter { it.category == category }.map { it.id }.toSet()

    /** Maps a build seed to the set of defects it activates. */
    fun defectsForSeed(seed: Int): Set<DefectId> = when {
        seed == 0 -> emptySet()
        seed == 99 -> DefectId.entries.toSet()
        seed in 1..DefectId.entries.size -> setOf(DefectId.entries[seed - 1])
        else -> emptySet()
    }
}
